[package]
name = "tcagm-dev/building-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Roact = "roblox/roact@1.4.4"
Util = "tcagm-dev/util@0.1.4"
Trove = "sleitnick/trove@1.4.0"
Promise = "evaera/promise@4.0.0"

[server-dependencies]
Database = "tcagm-dev/database@0.2.0"
Leaderstat = "tcagm-dev/leaderstat@0.1.0"